minimumReleaseAge: 10080
minimumReleaseAgeExclude: []

allowBuilds:
  ffmpeg-static: true
  onnxruntime-node: true
dlxCacheMaxAge: 259200 # 180 days in minutes, extended for pnpm dlx jiti
packages:
  - skills/*
updateNotifier: false
