env:
  CI: "true"
  DO_NOT_TRACK: "1"
jobs:
  check:
    name: Check and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/prepare
      - uses: rharkor/caching-for-turbo@0abc2381e688c4d2832f0665a68a01c6e82f0d6c # v2.3.11
        env:
          # Remove once https://github.com/rharkor/caching-for-turbo/issues/829 is resolved
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
      - run: pnpm check-and-test

name: CI

on:
  pull_request: ~
  push:
    branches:
      - main
